

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: api_service
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app  
    depends_on:
      - database 


  database:
    image: mongo:latest  
    container_name: mongo_db
    volumes:
      - ./data:/data/db  
    ports:
      - "27017:27017"  

